### ISSUE TITLE
how many non-flowering

### ISSUE THREAD

**Issue by rvosa** [naturalis/brassica-snps#7]
Discrepancy in Frederic's text and the spreadsheet

**Comment by fredericlens** [comment]
if you share the text with the discrepancy, I will take a look at it.

**Comment by rvosa** [comment]
In the manuscript (i.e. your word doc):

> **Selection of bulk segregant analysis (BSA): flowering time variation in F1**
> [ ... ]
> the fourth bulk (non flowering at the time of DNA extraction) included 9 F1s that only flowered after DNA extraction (up to 533 days after potting)

In the [spreadsheet](https://github.com/naturalis/brassica-snps/raw/master/results/phenotyping/histogram_flowering_time_Brassica_F1.xlsx):

|Flowering date per accession|Days to flowering***|F1 Accessions|Nr of F1 accessions|flowering time batch|
|--------|---|------------------------------------------------------------------------|--|-------------|
|28-05-18|294|17102, 17109, 17112**, 17118, 17120, 17121, 17122, 17127, 17130**, 17208|10|non flowering|
|18-06-18|315|17112**|1|"non" flowering after experiment|
|01-07-18|328|17130**|1|"non" flowering after experiment|
|07-10-18|456|17208**|1|"non" flowering after experiment|

...i.e. I guess I am counting 13?

**Comment by fredericlens** [comment]
Hi Rutger, 
Sorry for the delay, but I found the time to answer your question.
There is some discrepancy between the file I have written for the internal lab project (to sequence DNA of the F1s) and the excell file, but I assume the excell file is correct. I also communicated with Karin van Veen (technician who is taken care of the plants) to have a final check.

In the NF batch, there were 10 accessions: 17102, 17109, 17112, 17118, 17120, 17121, 17122, 17127, 17130, 17208. Of these, the 17102 individual had to be removed before it could flower because of a thrips infection (the growth chamber needed to be disinfected), so we do not have a flowering time for that one (probably later than the latest flowering though).

The accessions 17101, 17106, 17111, 17305 were not included because we wanted to have a time gap between late flowering and non-flowering.

Hope this helps, cheers, Frederic
